### ISSUE TITLE
Accept non-static argument for init()

### ISSUE THREAD

**Issue by bestouff** [quadrupleslap/badlog#1]
Let's say I'm taking my log level from a command-line argument:
```
error: `matches` does not live long enough
   --> src/main.rs:269:18
    |
269 |     badlog::init(matches.value_of("debug-level").unwrap());
    |                  ^^^^^^^ does not live long enough
...
373 | }
    | - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error: aborting due to previous error
```

**Comment by bestouff** [comment]
Note that this doesn't work either (if you need a simpler testcase):
```rust
    let log_level = "info".to_string();
    badlog::init(log_level);
```

**Comment by quadrupleslap** [comment]
Is this what you had in mind?

**Comment by bestouff** [comment]
I didn't try it yet, but from the look of it yes, indeed.

**Comment by quadrupleslap** [comment]
Okay, closing for now then!

**Comment by bestouff** [comment]
... and after a try in my code it works perfectly.
Could you re-relase the crate please ?

**Comment by quadrupleslap** [comment]
I think I already did. Did you update the version in `Cargo.toml` to `0.2.3`?

**Comment by bestouff** [comment]
Yes indeed, and it worked well. Thanks @quadrupleslap !
