### ISSUE TITLE
Do not paint() when redirecting to a file

### ISSUE THREAD

**Issue by bestouff** [quadrupleslap/badlog#2]
Could you please check if stdout is really a terminal, and if it's not the case just print plain text ? Colored text files are hard to use.

**Comment by quadrupleslap** [comment]
Uhh, sure, good idea.

**Comment by quadrupleslap** [comment]
Done! It just outright ignores Windows for now, though, even if it's Windows 10, which apparently supports ANSI codes.

**Comment by bestouff** [comment]
Thanks !
